### ISSUE TITLE
How to enter desktop environment

### ISSUE THREAD

**Issue by notaf0e** [nabakdev/dotfiles#1]
Hopefully this is not a stupid question. 😅
I installed endeavour os terminal version and the needed packages with the 2 commands. How do I enter the desktop environment from here? (I'm new to arch)

**Comment by nabakdev** [comment]
in case you don't know how to start Hyprland after 4 days (sorry i'm late :smile: ), simply type 'Hyprland' to start it

**Comment by notaf0e** [comment]
yep, thx
