### ISSUE TITLE
how to activate it?

### ISSUE THREAD

**Issue by rainbow-bash** [nabakdev/dotfiles#2]
hello im really new into arch and this stuff and i dont know how can i activate yiour configuration cause rn is still the default, i did both steps and tried rebooting but nothing :sob: i dont know if it was necesary to be in a clean clean arch install cause i used the hyperland from the archinstall

**Comment by ionicmc-js** [comment]
Hey! you need to copy 
the files into the config and make sure you downloaded everything,
(make sure you choose replace)
