### ISSUE TITLE
Pull Request on battery indicator in waybar

### ISSUE THREAD

**Issue by nadeemohc** [nabakdev/dotfiles#6]
Hey there @nabakdev  

I've added a pull request for the functionality of the battery percentage indicator in the waybar.
and it's currently waiting for your review, and I'll attach an image of it below as reference.

Happy coding :)
![screenshot-2024-06-26-19:26:25](https://github.com/nabakdev/dotfiles/assets/108587101/966f2363-7861-4272-8a29-5f94095d3453)

**Comment by nabakdev** [comment]
Sorry, I'm using EWW right now, and I'll rebase my repo later

**Comment by nadeemohc** [comment]
Okay cool
